# Generated by Django 5.1.7 on 2025-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_percentage',
            field=models.FloatField(default=0),
        ),
    ]
